aliases:
  - &tag-only
    filters:
      tags:
        only: /^v.*/
      branches:
        ignore: /.*/

  - &only-master
    filters:
      branches:
        only: master

  - &not-master
    filters:
      branches:
        ignore: master

version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}	  
          - v1-dependencies-

      - run: npm install
      - run: npm run test-ci
      - run: npm run report-coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  tag:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release
  push:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: test
          <<: *not-master
  tag:
    jobs:
      - test:
          context: test
          <<: *only-master
      - tag:
          context: tag
          <<: *only-master
          requires:
            - test
  deploy:
    jobs:
      - test:
          context: test
          <<: *tag-only
      - push:
          context: tag
          <<: *tag-only
          requires:
            - test
