aliases:
  - &tag-only
    filters:
      tags:
        only: /^v.*/
      branches:
        ignore: /.*/

  - &only-master
    filters:
      branches:
        only: master

  - &not-master
    filters:
      branches:
        ignore: master

version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}	  
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run test
          command: npm run test
      - run: npx semantic-release

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
            
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          context: test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          context: tag
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
