const i18ncountries = require('i18n-iso-countries')

module.exports.PAGINATION = {
	defaultPage: 0,
	defaultCount: 15,
	maxCount: 100
}
module.exports.LANGUAGES_ENUM = {
	en: 'en',
	es: 'es',
	de: 'de'
}
module.exports.LANGUAGES = Object.keys(exports.LANGUAGES_ENUM)

module.exports.USERROLES_ENUM = {
	ADMIN: 'ADMIN',
	COMPANY_OWNER: 'COMPANY_OWNER',
	EMPLOYEE: 'EMPLOYEE',
	CONSUMER: 'CONSUMER'
}
module.exports.USERROLES = Object.keys(exports.USERROLES_ENUM)

module.exports.FILE_EXTENSIONS_ENUM = {
	jpeg: 'jpeg',
	bmp: 'bmp',
	jpg: 'jpg',
	png: 'png',
	pdf: 'pdf',
	heic: 'heic'
}
module.exports.FILE_EXTENSIONS = Object.keys(exports.FILE_EXTENSIONS_ENUM)

module.exports.UNITS_ENUM = {
	CENTILITRE: 'CENTILITRE',
	CENTIMETRE: 'CENTIMETRE',
	CUBIC_DECIMETRE: 'CUBIC_DECIMETRE',
	CUBIC_METRE: 'CUBIC_METRE',
	DECIMETRE: 'DECIMETRE',
	GRAM: 'GRAM',
	INCH: 'INCH',
	KILOGRAM: 'KILOGRAM',
	LITRE: 'LITRE',
	METRE: 'METRE',
	MILLIGRAM: 'MILLIGRAM',
	MILLILITRE: 'MILLILITRE',
	PIECES: 'PIECES',
	POUNDS: 'POUNDS',
	PRODUCT: 'PRODUCT',
	SQUARE_CENTIMETRE: 'SQUARE_CENTIMETRE',
	SQUARE_DECIMETRE: 'SQUARE_DECIMETRE',
	SQUARE_INCH: 'SQUARE_INCH',
	SQUARE_METRE: 'SQUARE_METRE',
	SQUARE_FEET: 'SQUARE_FEET',
	STONE: 'STONE',
	SHORT_TON: 'SHORT_TON',
	LONG_TON: 'LONG_TON',
	HUNDREDWEIGHT: 'HUNDREDWEIGHT',
	SHORT_HUNDREDWEIGHT: 'SHORT_HUNDREDWEIGHT',
	LONG_HUNDREDWEIGHT: 'LONG_HUNDREDWEIGHT',
	OUNCE: 'OUNCE',
	DRAM: 'DRAM',
	GRAIN: 'GRAIN',
	PENNYWEIGHT: 'PENNYWEIGHT',
	SCRUPLE: 'SCRUPLE',
	GALLON: 'GALLON',
	QUART: 'QUART',
	PINT: 'PINT',
	GILL: 'GILL',
	FLUID_OUNCE: 'FLUID_OUNCE',
	FLUID_DRAM: 'FLUID_DRAM',
	MINIM: 'MINIM',
	BUSHEL: 'BUSHEL',
	PECK: 'PECK',
	NAUTICAL_MILE: 'NAUTICAL_MILE',
	MILE: 'MILE',
	FURLONG: 'FURLONG',
	ROD: 'ROD',
	FATHOM: 'FATHOM',
	YARD: 'YARD',
	FOOT: 'FOOT',
	SQUARE_MILE: 'SQUARE_MILE',
	ACRE: 'ACRE',
	SQUARE_ROD: 'SQUARE_ROD',
	SQUARE_YARD: 'SQUARE_YARD',
	CUBIC_YARD: 'CUBIC_YARD',
	CUBIC_FOOT: 'CUBIC_FOOT',
	CUBIC_INCH: 'CUBIC_INCH',
	ACRE_FOOT: 'ACRE_FOOT',
	CORD: 'CORD'
}
module.exports.UNITS = Object.keys(exports.UNITS_ENUM)

module.exports.COUNTRIES = Object.keys(i18ncountries.getAlpha2Codes())

module.exports.MATERIAL_CATEGORIES_ENUM = {
	NATURAL: 'NATURAL',
	VEGAN: 'VEGAN',
	INNOVATIVE: 'INNOVATIVE',
	RECYCLED: 'RECYCLED'
}
module.exports.MATERIAL_CATEGORIES = Object.keys(exports.MATERIAL_CATEGORIES_ENUM)

module.exports.SEARCH_ASSET_TYPE_ENUM = {
	MATERIAL: 'MATERIAL',
	CERTIFICATE: 'CERTIFICATE',
	BRAND: 'BRAND',
	SUPPLIER: 'SUPPLIER',
	MANUFACTURER: 'MANUFACTURER'
}
module.exports.SEARCH_ASSET_TYPE = Object.keys(exports.SEARCH_ASSET_TYPE_ENUM)

module.exports.APPROVALSTATUS_ENUM = {
	PENDING: 'PENDING',
	REQUESTED: 'REQUESTED',
	APPROVED: 'APPROVED',
	REJECTED: 'REJECTED',
	ABANDONED: 'ABANDONED'
}
module.exports.APPROVALSTATUS = Object.keys(exports.APPROVALSTATUS_ENUM)
